export const earningsData = [
  { name: "Jan", main: 70, secondary: 60 },
  { name: "Feb", main: 40, secondary: 55 },
  { name: "Mar", main: 20, secondary: 50 },
  { name: "Apr", main: 90, secondary: 52 },
  { name: "May", main: 150, secondary: 60 },
  { name: "Jun", main: 50, secondary: 65 },
  { name: "Jul", main: 60, secondary: 55 },
  { name: "Aug", main: 70, secondary: 50 },
  { name: "Sep", main: 80, secondary: 52 },
  { name: "Oct", main: 65, secondary: 56 },
  { name: "Nov", main: 70, secondary: 60 },
  { name: "Dec", main: 75, secondary: 62 },
];

export const earningsData2 = [
  { name: "Jan", value: 1500 },
  { name: "Feb", value: 2500 },
  { name: "Mar", value: 2200 },
  { name: "Apr", value: 4400 },
  { name: "May", value: 2100 },
  { name: "Jun", value: 2300 },
  { name: "Jul", value: 2500 },
  { name: "Aug", value: 2400 },
];

export const overview = [
  { month: "Jan", value: 1500 },
  { month: "Feb", value: 4800 },
  { month: "Mar", value: 1200 },
  { month: "Apr", value: 5000 },
  { month: "May", value: 3000 },
  { month: "Jun", value: 3500 },
  { month: "Jul", value: 4700 },
  { month: "Aug", value: 2800 },
  { month: "Sep", value: 800 },
  { month: "Oct", value: 3200 },
  { month: "Nov", value: 1600 },
  { month: "Dec", value: 3100 },
];

export const weeklyEarnings = [
  { day: "Mo", high: 300, low: 200 },
  { day: "Tu", high: 250, low: 150 },
  { day: "We", high: 450, low: 280 },
  { day: "Th", high: 520, low: 350 },
  { day: "Fr", high: 300, low: 200 },
  { day: "Sa", high: 350, low: 260 },
  { day: "Su", high: 380, low: 310 },
];

export const subscriptionsData = [
  { name: "Mo", value: 0 },
  { name: "Tu", value: 45 },
  { name: "We", value: 60 },
  { name: "Th", value: 40 },
  { name: "Fr", value: 30 },
  { name: "Sa", value: 50 },
  { name: "Su", value: 30 },
];

export const data = [
  { day: "Mo", actual: 200, projected: 290 },
  { day: "Tu", actual: 150, projected: 280 },
  { day: "We", actual: 260, projected: 450 },
  { day: "Th", actual: 350, projected: 510 },
  { day: "Fr", actual: 200, projected: 330 },
  { day: "Sa", actual: 280, projected: 400 },
  { day: "Su", actual: 310, projected: 390 },
];

export const StatsEarningData = [
  { date: "Nov 20", current: 120, previous: 80 },
  { date: "Nov 22", current: 110, previous: 95 },
  { date: "Nov 24", current: 115, previous: 90 },
  { date: "Nov 26", current: 130, previous: 85 },
  { date: "Nov 28", current: 122, previous: 70 },
  { date: "Nov 30", current: 118, previous: 78 },
  { date: "Dec 2", current: 125, previous: 92 },
  { date: "Dec 4", current: 120, previous: 100 },
  { date: "Dec 6", current: 128, previous: 105 },
  { date: "Dec 8", current: 135, previous: 110 },
  { date: "Dec 10", current: 130, previous: 108 },
  { date: "Dec 12", current: 138, previous: 115 },
  { date: "Dec 14", current: 150, previous: 120 },
  { date: "Dec 16", current: 145, previous: 130 },
  { date: "Dec 18", current: 155, previous: 140 },
  { date: "Dec 20", current: 160, previous: 155 },
];

export const chartData = [
  { month: "Jan", value: 8 },
  { month: "Feb", value: 5 },
  { month: "Mar", value: 3 },
  { month: "Apr", value: 2 },
  { month: "May", value: 1 },
  { month: "Jun", value: 3 },
  { month: "Jul", value: 4 },
  { month: "Aug", value: 2 },
  { month: "Sep", value: 1 },
  { month: "Oct", value: 3 },
  { month: "Nov", value: 7 },
  { month: "Dec", value: 10 },
];

// ================= MOCK PRODUCTS DATABASE =================
export let products = [
  {
    id: 1,
    productName: "iPhone 12 Pro",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 32,
    category: "Smartphone",
    description:
      "Premium smartphone with A14 Bionic chip and Pro camera system.",
    tags: ["apple", "smartphone", "iphone", "ios"],
    discount: 10,
    discountCategory: "Festival Sale",
  },
  {
    id: 2,
    productName: "Macbook Pro 2023",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 18,
    category: "Laptop",
    description: "High-performance laptop with M2 Pro chip for creators.",
    tags: ["apple", "laptop", "macbook", "m2"],
    discount: 15,
    discountCategory: "New Year Deal",
  },
  {
    id: 3,
    productName: "Samsung Galaxy S22",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 41,
    category: "Smartphone",
    description: "Flagship Samsung device with top-tier camera performance.",
    tags: ["samsung", "android", "galaxy"],
    discount: 5,
    discountCategory: "Flash Sale",
  },
  {
    id: 4,
    productName: "Dell XPS 13",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 21,
    category: "Laptop",
    description: "Compact ultrabook with premium build and long battery life.",
    tags: ["dell", "laptop", "xps"],
    discount: 8,
    discountCategory: "Student Discount",
  },
  {
    id: 5,
    productName: "Sony WH-1000XM5",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 54,
    category: "Audio",
    description: "Industry-leading noise cancelling wireless headphones.",
    tags: ["sony", "audio", "headphones"],
    discount: 12,
    discountCategory: "Holiday Sale",
  },
  {
    id: 6,
    productName: "Apple Watch Series 7",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 12,
    category: "Wearable",
    description: "Redesigned always-on display with advanced health tracking.",
    tags: ["apple", "wearable", "watch"],
    discount: 7,
    discountCategory: "Limited Offer",
  },
  {
    id: 7,
    productName: "Google Pixel 7",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 27,
    category: "Smartphone",
    description: "Google flagship with Tensor G2 chip and amazing camera.",
    tags: ["google", "android", "pixel"],
    discount: 6,
    discountCategory: "Launch Offer",
  },
  {
    id: 8,
    productName: "HP Spectre x360",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 17,
    category: "Laptop",
    description: "Premium convertible laptop with touchscreen and stylus.",
    tags: ["hp", "laptop", "spectre"],
    discount: 14,
    discountCategory: "Seasonal Offer",
  },
  {
    id: 9,
    productName: "Apple AirPods Pro",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 43,
    category: "Audio",
    description: "Noise cancelling earbuds with spatial audio support.",
    tags: ["apple", "audio", "airpods"],
    discount: 5,
    discountCategory: "Clearance",
  },
  {
    id: 10,
    productName: "Microsoft Surface Laptop 4",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 15,
    category: "Laptop",
    description: "Sleek design with smooth touch performance and Windows 11.",
    tags: ["microsoft", "laptop", "surface"],
    discount: 10,
    discountCategory: "Corporate Sale",
  },
  {
    id: 11,
    productName: "OnePlus 9 Pro",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 38,
    category: "Smartphone",
    description: "Flagship killer with Hasselblad camera tuning.",
    tags: ["oneplus", "android"],
    discount: 9,
    discountCategory: "Festival Sale",
  },
  {
    id: 12,
    productName: "GoPro Hero 10 Black",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 26,
    category: "Camera",
    description: "Premium action camera with 5.3K recording.",
    tags: ["gopro", "camera", "action"],
    discount: 11,
    discountCategory: "Adventure Week",
  },
  {
    id: 13,
    productName: "Razer Blade 15",
    views: 14000,
    pricing: 1.0,
    revenue: 164.0,
    stock: 22,
    category: "Gaming",
    description: "High-performance gaming laptop with RTX graphics.",
    tags: ["razer", "gaming", "laptop"],
    discount: 13,
    discountCategory: "Gamer Fest",
  },
];

export const API_URL = "http://localhost:3000/";
